### ISSUE TITLE
Fail downloading files 

### ISSUE THREAD

**Issue by araymund83** [PredictiveEcology/LandR-modules#2]
I change my change path, and now BorealDataPrep needs to download everything again. It started with ecodistricts so I download the zip file, put it into my google Drive and downloaded it to BC.  I did that for the stand age and some of the other .tif .  But now I have the nabc file failing.
```

Downloading https://cwfis.cfs.nrcan.gc.ca/downloads/nbac/nbac_1986_to_2018_20191129.zip ...
Downloading: 16 kB     Error in dlGeneric(url = url, needChecksums = needChecksums, destinationPath = .tempPath) : 
  Not Found (HTTP 404).
In addition: Warning messages:
1: In FUN(...) : studyArea and rasterToMatch projections differ.
studyArea will be projected to match rasterToMatch
2: In FUN(...) : studyAreaLarge and rasterToMatchLarge projections differ.
studyAreaLarge will be projected to match rasterToMatchLarge```

**Comment by tati-micheletti** [comment]
The address is wrong:

**Comment by tati-micheletti** [comment]
The address is wrong:
![image](https://user-images.githubusercontent.com/33500569/99311971-3a71f000-2812-11eb-8ad5-be727887bd7c.png)
The file doesn't exist in this address. This is not a prepInputs bug.

If you check the webpage you will see they updated the URL: https://cwfis.cfs.nrcan.gc.ca/downloads/nbac/nbac_1986_to_2019_20200921.zip
This one should work (provided the files don't have bugs)

**Comment by tati-micheletti** [comment]
The file doesn't exist in this address.

**Comment by tati-micheletti** [comment]
@araymund83 , can you please update the URL and make a PR to fix it? Thank you!
